name: Publish Pact Files
description: Publish pact files to pact broker
inputs:
  target:
    description: Pact files location
    default: pacts/
    required: true
  version:
    required: true
  broker_url:
    description: Pact Broker URL
    required: true
  broker_username:
    required: true
  broker_password:
    required: true
runs:
  using: composite
  steps:
    - run: |
        echo "PACT_TARGET=${{ inputs.target }}" >> $GITHUB_ENV
        echo "PACT_VERSION=${{ inputs.version }}" >> $GITHUB_ENV
        echo "PACT_BROKER_URL=${{ inputs.broker_url }}" >> $GITHUB_ENV
        echo "PACT_BROKER_USERNAME=${{ inputs.broker_username }}" >> $GITHUB_ENV
        echo "PACT_BROKER_PASSWORD=${{ inputs.broker_password }}" >> $GITHUB_ENV
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: run.sh
      shell: bash
